server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  data:
    mongodb:
      uri: mongodb://localhost:27017/demo
      database: demo
management:
  endpoints:
    web:
      exposure:
        include: health,info
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    persistAuthorization: false
    url: /openapi/openapi.yaml
logging:
  level:
    com.demo: DEBUG
external:
  availability:
    base-url: https://demo.com/api/bookings/checkAvailable
    connect-timeout-ms: 1000
    response-timeout-ms: 3000
    read-timeout-ms: 3000
    write-timeout-ms: 3000