apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-service
  namespace: maersk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: container-service
  template:
    metadata:
      labels:
        app: container-service
    spec:
      containers:
        - name: container-service
          image: __ACR__.azurecr.io/container-service:__TAG__
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: container-secrets
                  key: mongo-uri
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 20
            periodSeconds: 20